#!/usr/bin/env node
// PreToolUse guard: block Edit/Write/MultiEdit on generated or cached files.
// Exits 2 to veto the tool call; stderr becomes the block reason shown to Claude.

const BLOCKED = [
	{
		pattern: /(^|\/)docs\/\.cache\//,
		reason: 'docs/.cache/ is a mechanically-derived local cache. Run `pnpm docs:fetch <url>` instead — any manual edit will be clobbered on the next fetch.',
	},
	{
		pattern: /(^|\/)worker-configuration\.d\.ts$/,
		reason: 'worker-configuration.d.ts is generated by `pnpm cf-typegen`. Edit wrangler bindings, then regenerate — do not edit this file directly.',
	},
	{
		pattern: /(^|\/)pnpm-lock\.yaml$/,
		reason: 'pnpm-lock.yaml must only change via `pnpm add/remove/update`. Do not edit it by hand.',
	},
]

const input = await new Promise((resolve) => {
	let d = ''
	process.stdin.on('data', (c) => (d += c))
	process.stdin.on('end', () => resolve(d))
})

let payload
try {
	payload = JSON.parse(input)
} catch {
	process.exit(0) // no payload, nothing to guard
}

const ti = payload.tool_input ?? {}
// Edit/Write use `file_path`; MultiEdit uses `file_path` for the single target.
const file = ti.file_path ?? ti.path
if (!file) process.exit(0)

const norm = String(file).replace(/\\/g, '/')

for (const { pattern, reason } of BLOCKED) {
	if (pattern.test(norm)) {
		console.error(`[block-paths] BLOCKED edit to ${norm}\n${reason}`)
		process.exit(2)
	}
}

process.exit(0)
